version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/elixir:1.5
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test

      - deploy:
          name: Maybe Deploy
          command: |
            ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push dokku@$DEPLOY_HOST:broad master
            fi
