version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/elixir:1.5
      - image: redis:3.2.10
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
