version: 2
jobs:
  build:
    working_directory: ~/image_vac
    docker:
      - image: elixir:1.5.1
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
