version: 2
jobs:
  build:
    working_directory: ~/repo
    parallelism: 1  # run only one instance of this job in parallel
    docker:
      - image: circleci/elixir:1.7.2
        environment:  # environment variables for primary container
          MIX_ENV: test
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: postgres
    steps:  # commands that comprise the `build` job
      - checkout  # check out source code to working directory

      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)

      - restore_cache:  # restores saved mix cache
          keys:  # list of cache keys, in decreasing specificity
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile  # get updated dependencies & compile them
      - save_cache:  # generate and store cache so `restore_cache` works
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:  # make another less specific cache
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:  # you should really save one more cache just in case
          key: v1-mix-cache
          paths: "deps"
      - save_cache: # don't forget to save a *build* cache, too
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache: # and one more build cache for good measure
          key: v1-build-cache
          paths: "_build"

      - run:  # special utility that stalls main process until DB is ready
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test  # run all tests in project

      - store_test_results:  # upload test results for display in Test Summary
          path: _build/test/junit


      - deploy:
          name: Maybe Deploy
          command: |
            ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push dokku@$DEPLOY_HOST:imagevac master
            fi
